# config/database.yml

# ... (keep the rest of your file as is, including 'default', 'development', and 'test' blocks) ...

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

cable:
  primary:
    url: <%= ENV.fetch('DATABASE_URL') %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

queue:
  primary:
    url: <%= ENV.fetch('DATABASE_URL') %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

cache:
  primary:
    url: <%= ENV.fetch('DATABASE_URL') %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#export DATABASE_URL="postgresql://miguel:olida@localhost:5432/linktreeclonedb"